name: ctrim_app_v1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0
  equatable: ^1.2.0
  file_picker: ^1.9.0+1
  zefyr: ^0.11.0
  quill_delta: ^1.0.2
  intl: ^0.16.1
  video_player: ^0.10.11+1
  geocoder: ^0.2.1
  photo_view: ^0.9.2
  path_provider: ^1.6.11
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  cupertino_icons: ^0.1.3
  google_maps_flutter: ^0.5.28+1
  firebase_storage: ^3.1.6
  url_launcher: ^5.5.0
  add_2_calendar: ^1.4.0
  flutter_icons: ^1.1.0
  video_thumbnail: ^0.2.2
  chewie: ^0.9.10
  firebase_messaging: ^6.0.16
  flutter_image: ^3.0.0
  package_info: ^0.4.1
  flutter_image_compress: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # fonts:
  #   - family: OpenSans
  #     fonts:
  #       - asset: assets/fonts/OpenSans-Regular.ttf
  #         weight: 400
  #   - family: MerriweatherSans
  #     fonts:
  #       - asset: assets/fonts/MerriweatherSans-Regular.ttf
  #         weight: 400


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
