name: ctrim_app_v1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.4.0+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0
  equatable: ^1.2.0
  file_picker: ^2.0.0
  zefyr: ^0.11.0
  quill_delta: ^1.0.2
  intl: ^0.16.1
  video_player: ^0.10.12+3
  geocoder: ^0.2.1
  photo_view: ^0.10.2
  path_provider: ^1.6.16

  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_messaging: ^7.0.0
  firebase_storage: ^4.0.0
  firebase_core: ^0.5.0

  cupertino_icons: ^0.1.3
  google_maps_flutter: ^0.5.32
  url_launcher: ^5.7.0
  add_2_calendar: ^1.4.0
  flutter_icons: ^1.1.0
  video_thumbnail: ^0.2.2
  chewie: ^0.9.10
  flutter_image: ^3.0.0
  package_info: ^0.4.1
  flutter_image_compress: ^0.7.0
  video_compress: ^2.0.0
  scroll_app_bar: ^1.0.2
  flutter_spinkit: ^4.1.2
  device_info: ^0.4.2+7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # fonts:
  #   - family: OpenSans
  #     fonts:
  #       - asset: assets/fonts/OpenSans-Regular.ttf
  #         weight: 400
  #   - family: MerriweatherSans
  #     fonts:
  #       - asset: assets/fonts/MerriweatherSans-Regular.ttf
  #         weight: 400

  assets:
    - assets/ctrim_logo.png
